### ISSUE TITLE
[Feature request] Trivial customisation / theming

### ISSUE THREAD

**Issue by jhc-at-home** [liaScript/LiaScript#1]
It would be nice to be able to add presentation theming hints in the markdown metadata that override the Lia theme.
e.g. 
* The "logo" could be displayed in the top bar (Not just in the courses cards).
* A foreground colour scheme of 2 colours. Something like:
```yaml
colors:
  - #abc
  - #00ff33
```
* A font. Something like:
```yaml
font: 
  - main:
    name: Fira Sans Condensed
    url: https://fonts.googleapis.com/css?family=Fira+Sans+Condensed&display=swap
```
or just
```yaml
font: https://fonts.googleapis.com/css?family=Fira+Sans+Condensed&display=swap
```

**Comment by jhc-at-home** [comment]
An alternative might be:
```yaml
theme:
  primary: #abc
  secondary: #00ff33
  text: red
  background: black
  font: https://fonts.googleapis.com/css?family=Fira+Sans+Condensed&display=swap
```
