### ISSUE TITLE
Q: define css class for embedding ORCID logo for author lists

### ISSUE THREAD

**Issue by abotzki** [LiaScript/LiaScript#129]
Hi,

Just wanted to ask whether you find such an approach useful. We thought about adding the link to the ORCID profile for all authors and contributors like on F1000. For an example: https://f1000research.com/articles/11-869

I see that they include this class definition in the css and use `<span class="orcid-logo-for-author-list"></span>`
 
.orcid-logo-for-author-list {
  background: transparent url(/img/icon/orcid_icon.png) center center no-repeat;
    background-color: transparent;
    background-position-x: center;
    background-position-y: center;
    background-repeat: no-repeat;
    background-attachment: scroll;
    background-image: url("/img/icon/orcid_icon.png");
    background-size: auto;
    background-origin: padding-box;
    background-clip: border-box;
  width: 16px;
  height: 16px;
  margin-left: 4px;
  margin-right: 2px;
  display: inline-block;
  vertical-align: middle;
}

What do you think?

**Comment by andre-dietrich** [comment]
Hi, and sorry for the late response, I have been updating our internal classroom, the chat can now interpret LiaScript directly ...

Adding this to a course should not be a big thing, as you can load custom (local) styles:

``` css
// style.css
.orcid-logo-for-author-list {
    display: inline-block;
    vertical-align: middle;
    position: relative;
    padding-right: 2.2rem;
}

.orcid-logo-for-author-list ::after {
    content: "";
    display: block;
    position: absolute;
    top: 50%;
    right: 3px;
    transform: translateY(-50%);
    background: transparent url(https://f1000research.com/img/icon/orcid_icon.png) center center no-repeat;
    background-image: url("https://f1000research.com/img/icon/orcid_icon.png");
    background-size: auto;
    width: 1.8rem;
    height: 1.8rem;
}
```

this file can be placed relative to the Markdown file and embedded as follows:

``` markdown
<!--

link: style.css

@orcid: [@0](@1)<!--class="orcid-logo-for-author-list"-->

-->

# ORCID

<a class="orcid-logo-for-author-list" href="http://orcid.org/0000-0001-8150-4021">Paulo Czarnewski</a>

---

@[orcid(Paulo Czarnewski)](http://orcid.org/0000-0001-8150-4021)
```
The result on my browser looks like this:

![image](https://user-images.githubusercontent.com/3089101/230373608-a8dca394-c2ae-495d-9266-bff42d94ebf9.png)

... and if you have defined such a Markdown, which contains all of your custom styles and your macros, you can reuse this by importing it to other courses via:

``` markdown
<!--
import: https://raw-url-to-orcid-ids.md
-->

# ...

<a class="orcid-logo-for-author-list" href="http://orcid.org/0000-0001-8150-4021">Paulo Czarnewski</a>
```

Does this answer your question?

I think it would be nice to have a collection of macros, which deal with common ORCID issues. In this case we could start with a simple issue list and then embed this functionality to a LiaScript-template ... 

What do you think ;-)
